### ISSUE TITLE
[HELP] RangeError: Maximum call stack size exceeded (in Angular 18) | there is an issue with "responsive properties"

### ISSUE THREAD

**Issue by dyazincahya** [apexcharts/ng-apexcharts#349]
### Using
- angular 18.1.0
- node.JS 22
- apexchart 3.52.0
- ng-apexchart 1.11.0

### Situation
This error appears when I try to display 2 or more dynamic charts in the same page.

### Error
I have an error like this 
```
RangeError: Maximum call stack size exceeded
    at Object.toString (zone.js:2850:37)
    at Function.value (apexcharts.common.js:6:4661)
    at Function.value (apexcharts.common.js:6:5483)
    at Function.value (apexcharts.common.js:6:5540)
    at Function.value (apexcharts.common.js:6:5694)
    at Function.value (apexcharts.common.js:6:5694)
    at Function.value (apexcharts.common.js:6:5694)
    at Function.value (apexcharts.common.js:6:5540)
    at Function.value (apexcharts.common.js:6:5694)
    at Function.value (apexcharts.common.js:6:5694)
```

**Comment by dyazincahya** [comment]
### [SOLVED]
This error is caused by the responsive property, 
```javascript
responsive: [
        {
          breakpoint: 480,
          options: {
            chart: {
              width: 200
            },
            legend: {
              position: "bottom"
            }
          }
        }
      ]
```
after I deleted the responsive property the chart appeared normally.

I think there is something in the responsive property, especially for pie and donut type charts.

**Comment by dr-bharada** [comment]
It true
![image](https://github.com/user-attachments/assets/907f5d98-83a7-4968-ae7d-3b20e0eafdc1)

**Comment by dyazincahya** [comment]
hmm

**Comment by krystijansen** [comment]
Has a solution been found for this? Experiencing the same thing using Vue3 and the responsive property on Pie/Donut charts.

**Comment by dyazincahya** [comment]
@krystijansen for temporary solution, try delete the ```responsive property``` and the chart will appeared normally.

**Comment by QuasiSquirrel** [comment]
I have come across this error as well using Blazor ApexCharts, the C# wrapper for the JavaScript library. Solution for me was to create two separate graphs and display them via responsive css, which is obviously not ideal. Would appreciate it if this could get fixed.

**Comment by JGex** [comment]
Same for me with Vue3 and `vue3-apexcharts`, but with the bar chart
I removed the `responsive` property, but it's clearly not a solution

**Comment by dyazincahya** [comment]
> ~Same for me with Vue3 and `vue3-apexcharts`, but with the bar chart~ ~I removed the `responsive` property, but it's clearly not a solution~
> 
> -> Ok, i've updated to 4.3 and I do not have the error with bar chart

Try donut or pie diagram

**Comment by QuasiSquirrel** [comment]
I've found a workaround to this issue by defining all of my options inside the responsive property, with the default options having a breakpoint of 90000 (or some other ridiculously high pixel count number). Since all I'm using is a Blazor wrapper for the Javascript library, I'll assume this workaround should work for other frameworks/vanilla as well.

The original issue still persists, but at least I don't have to duplicate my graphs with different options.
